# Site settings
title: David Hopson's CV 
description: David Hopson's CV
favicon: /assets/img/avatar.JPG
baseurl: 
url: http://localhost
rss_url: /pages/atom.xml
google_analytics: UA-63653234-1

# Build settings
markdown: kramdown

exclude: [vendor]

# Author settings
author:
  name: David Hopson
  title: NodeJS Developer
  address: West Yorkshire, UK
  email: mantle@hotmail.co.uk
  link: https://github.com/darkmantle
  weibo:
  github: darkmantle
  linkedin: davidhopson90
  gavatar: /assets/img/avatar.JPG
  stackoverflow:
  workHistory:
    - work1:
      company: Itap Group
      location: London, UK
      title: Software Developer Developer
      started: 2018
      duration: Mar 2018 - Jul 2020
      description: I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description.
    - work2:
      company: Chooz.Pics
      location: London, UK
      title: Chief Technology Officer
      started: 2016
      duration: Jun 2016 - Mar 2018
      description: I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description.
    - work3:
      company: Self-Employed
      location: England, UK
      title: Java Developer
      started: 2012
      duration: (2012 - 2014)
      description: I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description.
  educationHistory:
    - education1:
      organization: University of Leeds
      location: Leeds, UK
      degree: Bachelor
      major: Computer Science
      started: 2012
      duration: 2012 - 2016
      description: I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description.
  programmingSkills:
    - skill1:
      name: NodeJS
      percentage: 100%
    - skill2:
      name: Angular
      percentage: 90%
    - skill3:
      name: React
      percentage: 80%
    - skill4:
      name: TypeScript
      percentage: 90%
    - skill5:
      name: React Native
      percentage: 65%
    - skill6:
      name: PHP
      percentage: 70%
